map_type: costmap

obstacle_range: 2.5 # 1.5 #2.2
raytrace_range: 3.0 # 3.0

transform_tolerance: 0.33 # 0.33 

footprint: [[0.12,0.26], [-0.12,0.26], [0.12,-0.26], [-0.12,-0.26]] #.26 .11
#robot_radius: 0.3 # 0.0
inflation_radius: 0.83 # 0.75
cost_scaling_factor: 5.0 #5.0

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
