local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint
   update_frequency: 4.0 #5
   publish_frequency: 4.0 #5 
   width: 7.0 #10
   height: 7.0 #10
   resolution: 0.1 #0.05
   static_map: true #false
   rolling_window: true #false
